[package]
name = "wyag-rust"
version = "0.1.0"
authors = ["nf <nflower@adaptiveplanningandexecution.com>"]
edition = "2018"

[dependencies]
rust-ini = "0.13"
flate2 = { version = "1.0", features = ["zlib"], default-features = false }
rust-crypto = "^0.2"
linked-hash-map = "0.5.2"
regex = "1"